import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css'
import AppTitle from '../Components/AppTitle';
import Navigation from '../Components/Navigation';
import {Table} from '../Components/Table';

export default function Home() {

  const router = useRouter();
  const years = ["2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015"];
  const [year, setYear] = useState(2003);

  useEffect(() => {
    let slug = router.query.year;
    if(!slug || !years.includes(slug)) {
      slug = "2003";
    }
    setYear(slug);
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Histórico do Brasileirão Série A</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

          <header className={styles.header}>
            <AppTitle year={year}/>
            <Navigation  activeYear={year} />
          </header>

          <div className={styles.contentConteiner}>
              <Table year={year}/>
          </div>

      </main>
    </div>
  )
}
