import Head from 'next/head'
import styles from '../styles/Home.module.css'

import AppTitle from '../Components/AppTitle';
import AppSelect from '../Components/AppSelect';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Histórico do Brasileirão Série A</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <AppTitle />
          <AppSelect />
        </header>
      </main>
    </div>
  )
}
