import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <header className={styles.header}>
          <Image  alt="Logo of CBF" className={styles.logo} src='/img/national-brazil.fw.png' width={50} height={71} />
          <div className={styles.headerTitle}>
            <h1 className={styles.title}>
              Histórico do Campeonato Brasileiro
            </h1>
            <p className={styles.subTitle}>
              Sistema de pontos corridos
            </p>
          </div>
        </header>
      </main>
    </div>
  )
}
